CETask/Models/Pupil.cs
using System;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace CETask.Models
{
    public class Pupil
    {
        [Required]
        [JsonProperty(PropertyName = "id")]
        public string id { get; set; }
        [JsonProperty(PropertyName = "EntryID")]
        [Required]
        public string EntryID { get; set; }
        [JsonProperty(PropertyName = "Grade")]
        [Required]
        public string Grade { get; set; }
        [JsonProperty(PropertyName = "Name")]
        [Required]
        public string Name { get; set; }

        public string Type { get => "Pupil"; }
    }
}

CETask/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace CETask.Models
{
    public class Teacher
    {
        [Required]
        [JsonProperty(PropertyName = "id")]
        public string id { get; set; }
        [Required]
        [JsonProperty(PropertyName = "EntryID")]
        public string EntryID { get; set; }
        [Required]
        [JsonProperty(PropertyName = "Subject")]
        public string Subject { get; set; }
        [Required]
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }
        [Required]
        [JsonProperty(PropertyName = "GradesString")]
        public string GradesString { get; set; }
        public string Type { get => "Teacher"; }
    }
}

CETask/Controllers/PupilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CETask.Interfaces;
using CETask.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos;



// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CETask.Controllers
{
    [Route("api/[controller]")]
    public class PupilController : Controller
    {
        private readonly ICosmosDbService _cosmosDbService;

        public PupilController(ICosmosDbService cosmosDbService)
        {
            _cosmosDbService = cosmosDbService ?? throw new ArgumentNullException(nameof(cosmosDbService));
        }
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var Pupils = await _cosmosDbService.GetMultiplePupilsAsync();

            if (Pupils != null)
            return Ok(Pupils);

            return NotFound();
        }

        [HttpGet("{id}")]
        public void Get(string id)
        {
           
        }

        [HttpPost]
        public void Post(Pupil pupil)
        {
          
             _cosmosDbService.AddPupilsync(pupil);

        }

        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

CETask/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CETask.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CETask.Controllers
{
    public class SignUpController : Controller
    {
        // GET: /<controller>/
        public IActionResult Teacher()
        {
            return View(new Teacher());
        }
        public IActionResult Pupil()
        {
            return View(new Pupil());
        }
    }
}

CETask/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CETask.Interfaces;
using CETask.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Cosmos;



// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CETask.Controllers
{
    [Route("api/[controller]")]
    public class TeacherController : Controller
    {
        private readonly ICosmosDbService _cosmosDbService;

        public TeacherController(ICosmosDbService cosmosDbService)
        {
            _cosmosDbService = cosmosDbService ?? throw new ArgumentNullException(nameof(cosmosDbService));
        }
        [HttpGet]
        public async Task<IActionResult> List()
        {
            var Teachers = await _cosmosDbService.GetMultipleTeachersAsync();

            if (Teachers!=null)
            return Ok(Teachers);

            return NotFound();
        }

        [HttpGet("{id}")]
        public void Get(string id)
        {
           
        }

        [HttpPost]
        public void Post(Teacher teacher)
        {

          
             _cosmosDbService.AddTeacherAsync(teacher);

        }

        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

CETask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Signing Up</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignUp" asp-action="Teacher">Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SignUp" asp-action="Pupil">Pupil</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CET Task
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CETask/Views/SignUp/Pupil.cshtml
@model Pupil
@{
    ViewData["Title"] = "Pupil Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
 
</div>



<form asp-controller="api" asp-action="Pupil" method="POST" class="needs-validation" novalidate>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="id"></label>
        <input class="form-control" asp-for="id" />
        <span asp-validation-for="id"></span>
    </div>
    <div class="form-group">
        <label asp-for="EntryID"></label>
        <input class="form-control" asp-for="EntryID" />
        <span asp-validation-for="EntryID"></span>
    </div>
    <div class="form-group">
        <label asp-for="Grade"></label>
        <input class="form-control" asp-for="Grade" />
        <span asp-validation-for="Grade"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

CETask/Views/SignUp/Teacher.cshtml
@model Teacher
@{
    ViewData["Title"] = "Teacher Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>



<form asp-controller="api" asp-action="Teacher" method="POST" class="needs-validation" novalidate>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="id"></label>
        <input class="form-control" asp-for="id" />
        <span asp-validation-for="id"></span>
    </div>
    <div class="form-group">
        <label asp-for="EntryID"></label>
        <input class="form-control" asp-for="EntryID" />
        <span asp-validation-for="EntryID"></span>
    </div>
    <div class="form-group">
        <label asp-for="Subject"></label>
        <input class="form-control" asp-for="Subject" />
        <span asp-validation-for="Subject"></span>
    </div>
    <div class="form-group">
        <h5>   Use ',' as a Divider - e.g : ח,ט,י,י-א</h5>
        <label asp-for="GradesString"></label>
        <input class="form-control" asp-for="GradesString" />
        <span asp-validation-for="GradesString"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>